// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrwalcwlzropiukppike.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yd2FsY3dsenJvcGl1a3BwaWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTkxMzQsImV4cCI6MjA1OTg3NTEzNH0.A7j046b3DcdWAxpltwP8loxJj5tZvKyrYW1gTcc72gw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);